import asyncio
import os
import sys
from mcp import ClientSession, StdioServerParameters
from mcp.client.stdio import stdio_client

async def run():
    print("Connecting to bridge...", file=sys.stderr)
    
    server_params = StdioServerParameters(
        command="python",
        args=["-m", "mind_kernel_mcp.bridge"],
        env=dict(os.environ)
    )

    try:
        async with stdio_client(server_params) as (read, write):
            async with ClientSession(read, write) as session:
                await session.initialize()
                
                print("Listing tools...", file=sys.stderr)
                tools = await session.list_tools()
                tool_names = [t.name for t in tools.tools]
                print(f"Tools found: {tool_names}", file=sys.stderr)
                
                if "update_mind_kernel_file" not in tool_names:
                    print("Error: update_mind_kernel_file not found!", file=sys.stderr)
                    sys.exit(1)
                
                # Use environment variable or CLI argument for user ID
                user_id = os.getenv("TEST_USER_ID")
                if len(sys.argv) > 1:
                    user_id = sys.argv[1]
                
                if not user_id:
                    print("Error: TEST_USER_ID env var or command line argument is required.", file=sys.stderr)
                    sys.exit(1)
                
                # Test Case: Propose update with change log and update summary
                print(f"Calling update_mind_kernel_file with userId='{user_id}'...", file=sys.stderr)
                arguments = {
                    "userId": user_id,
                    "version": "v1.2.3",
                    "commitMessage": "Test update via MCP",
                    "jsonPatch": [
                        # Use replace operation to avoid assertion errors and create a valid PR
                        { "op": "replace", "path": "/version", "value": "2025-12-08-origin-story-v2.2-test-update" }
                    ],
                    "changeLogEntry": "## [Test] - v0.0.0\n- Test update executed.",
                    "prBody": "This is a test PR generated by MCP",
                    "updateSummary": {
                        "test_key": "test_value"
                    }
                }
                
                # Note: This will fail if core.json doesn't exist or patch path is invalid in the repo,
                # but we just want to see if it tries to call GitHub API correctly.
                # Since we don't have a real GitHub token in the seeded DB (presumably), 
                # or network access might be restricted, we expect an error or a mock response.
                # However, if using real token, it would work.
                
                try:
                    result = await session.call_tool("update_mind_kernel_file", arguments=arguments)
                    
                    if result.content and len(result.content) > 0:
                        print("\n--- Result Content ---")
                        print(result.content[0].text)
                        print("----------------------\n")
                    else:
                        print("Empty result content.")
                except Exception as e:
                     print(f"Tool execution error (expected if no valid token): {e}", file=sys.stderr)


    except Exception as e:
        print(f"Test failed: {e}", file=sys.stderr)
        sys.exit(1)

if __name__ == "__main__":
    asyncio.run(run())
